- Vagrantfile
Minor version numbers have been removed from Rackspace CentOS image names.
There are also some "OnMetal" images, so specify PV specifically to avoid
matching them.
---
<pre>
CentOS 5 (PV) 
CentOS 6 (PV) 
CentOS 6 (PVHVM) 
CentOS 7 (PVHVM) 
Debian 6 (Squeeze) (PV) 
Debian 7 (Wheezy) (PVHVM) 
Debian Testing (Jessie) (PVHVM) 
Debian Unstable (Sid) (PVHVM) 
Fedora 19 (Schrodinger's Cat) (PVHVM) 
Fedora 20 (Heisenbug) (PVHVM) 
Fedora 21 (PVHVM) 
OnMetal - CentOS 6 
OnMetal - CentOS 7 
OnMetal - Debian 7 (Wheezy) 
OnMetal - Debian Testing (Jessie) 
OnMetal - Debian Unstable (Sid) 
OnMetal - Fedora 20 (Heisenbug) 
OnMetal - Ubuntu 12.04 LTS (Precise Pangolin) 
OnMetal - Ubuntu 14.04 LTS (Trusty Tahr) 
OnMetal - Ubuntu 14.10 (Utopic Unicorn) 
Ubuntu 10.04 LTS (Lucid Lynx) (PV) 
Ubuntu 12.04 LTS …
> Remove minor version from Rackspace EL6 image name, find PV version

- fb-install-foreman.bats
Previously generated this output on Ubuntu 14.04:
(from function `tPackageUpgrade' in file /usr/bin/os_helper.bash, line 102,
in test file /usr/bin/fb-install-foreman.bats, line 81)
`tPackageUpgrade bash openssh ca-certificates sudo selinux-policy\* yum\* abrt\* sos' failed with status 100
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package openssh
E: Unable to locate package sos
> Fix package names for Debian based OSes

- fb-setup-libvirt.bats
One note - for nested libvirt via Foreman you are missing last bit - to be able
to define CPU features in the UI. It will always fail with "Call to
virDomainDefineXML failed: unknown OS type hvm" because CPU type must be set to
"host" or to have hypervisor capability.
I briefly searched in fog/libvirt but I was unable to find how to provide this
bit. If you know how to do that, please do the patch for me into Foreman :-)
> Fixed pool starting and kickstart option

- fb-install-foreman.bats
Previously it would try and install foreman-release.rpm from the primary
yum.tf.org repos, which wouldn't exist for a brand new release yet.
Now when using a custom repo, simply install foreman-release from there
instead.
(foreman-release is used as it helps configure the plugin repos)
---
Sorry, a bit of an urgent one to be able to release RC1.  I've no idea how I managed to do 1.7.0-RC1 last time, unless I just pushed it despite the initial test failure, or this code was different.
http://ci.theforeman.org/job/systest_foreman/5912/console is the failed run.  Seems to work from vagrant here:
<pre>
✔ ~/code/foreman/foreman-bats [custom-release-rpm L|…2⚑ 3] 
08:26 $ echo FOREMAN_CUSTOM_URL=http://koji.katello.org/releases/yum/foreman-1.8/RHEL/7/x86_64/ FOREMAN_REPO=releases/1.8 …
> Install foreman-release from custom repo

- fb-setup-libvirt.bats
For some reason, puppet agent exits with "2" on success (RHEL6). Help page says
nothing about exit codes and only mention the special `--detailed-exitcodes`
which we do not provide. Google also tells me nothing. Because agent return
codes are not important for our tests, I am giving it true.
```
✗ refresh puppet facts
(in test file fb-setup-libvirt.bats, line 86)
`puppet agent -t -v' failed with status 2
info: Retrieving plugin
info: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
info: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
info: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
info: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
info: Caching catalog for hp-dl580g7-02.rhts.eng.bos.redhat.com
info: Applying configuration version …
```
> Do not fail on agent exit code 2

- fb-install-foreman.bats
The proposed fix for upstream is not to reference the directory which isn't
brought or created by the packages in fileserver.conf. Here it's much easier
just to create the directory.
See http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=782325 for the Debian bug report and i.e. http://ci.theforeman.org/view/Status/job/systest_foreman/6125/console for the actual problem.
> add workaround for Debian bug #782325

- bootstrap_vagrant.sh
- fb-install-foreman.bats
- os_helper.bash
This works better as it upgrades other necessary packages.  Also fixed the
name of the ssh package, as 'ssh' has long been obsolete and isn't actually
the OpenSSH client's package name.
---
The hope is that it fixes this error: http://ci.theforeman.org/job/systest_foreman/6178/tapTestReport/fb-install-foreman.bats.out-6/
I tested it manually:
<pre>
root@jessietest1:~# dpkg -l openssh*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-======================== …
> Use apt-get --only-upgrade instead of apt-get upgrade

- README.md
- fb-install-foreman.bats
- fb-puppet-tests.bats
- fb-setup-libvirt.bats
Trying to cut down on the contents of fb-install-foreman.bats, and lay the way for doing an upgrade task followed by tests (instead of tests being part of installation).
> Move Foreman/Puppet integration tests to their own file

- fb-install-foreman.bats
Hammer wasn't getting exercised in the package installation test, but should.
Also check the webapp's responding still after CR installation.
> Check smart proxy is registered via Hammer

- fb-install-foreman.bats
When using a custom Yum repo URL, use the foreman-release repo
definition inside after updating the URL to access the custom repo.
This ensures GPG check and key settings from the repo under test are
used so we pick up on any signature issues.
> refs #12230 - use foreman-release Yum repo GPG config

- Vagrantfile
- os_helper.bash
Packages are built on Koji and a run against Rackspace locally (with FOREMAN_CUSTOM_URL etc.) seems to be OK:
<pre>
15:57 $ vagrant ssh f21 -c 'FOREMAN_CUSTOM_URL=http://koji.katello.org/releases/yum/foreman-nightly/Fedora/21/x86_64/ /vagrant/fb-install-foreman.bats'
✓ stop puppet agent (if installed)
✓ clean after puppet (if installed)
✓ make sure puppet not configured to other pm
✓ wait max 30 secs until network is up
✓ install SELinux tools
✓ update important system packages
- subscribe and attach channels (skipped: Not required)
- enable epel (skipped: Not required)
✓ configure repository
✓ install installer
✓ run the installer
✓ check for no changes when running the installer
✓ wait 10 seconds
✓ check web app is up
✓ check smart proxy is registered and Hammer runs
✓ install all …
> Add Fedora 21 support

- README.md
- Vagrantfile
Default configuration requires 2GB physical RAM for the service to
start, so when PC1/nightly repos are in use, increase VM memory.
> Increase RAM in test VMs for Puppet Server

- fb-puppet-tests.bats
Ensures that when trying to test specific PL repos that the
installation doesn't silently fall back to an OS package causing the
test to pass.
> Add test to check installed Puppet package vendor

- fb-install-plpuppet.bats
Should fix: http://ci.theforeman.org/job/systest_foreman/9501/console
The key on the website is expired ([CPR-347](https://tickets.puppetlabs.com/browse/CPR-347)) so the version on the keyserver is necessary for now.
> Configure PL nightly GPG key to authenticate packages

- fb-puppet-tests.bats
Newer AIO installations use /etc/puppetlabs/code as the base for
modulepaths, so tests must install modules to this location if it
exists.
> Prefer modulepath in /etc/puppetlabs/code under AIO

- fb-puppet-tests.bats
Contains https://github.com/puppetlabs/puppetlabs-ntp/commit/930066d
which fixes:
Parameter name failed on Package[ntp]: Name must be a String not
Array at modules/ntp/manifests/install.pp:4
and retains Puppet 2.7 support for older release tests.
> Update puppetlabs/ntp for Puppet 4 compatibility

- fb-install-foreman.bats
Since 92d8a0d tests on Debian failed as the service may not be
installed.
> Ignore failures stopping iptables when absent

- Vagrantfile
Some Rackspace images containing a pre-installed version of Puppet
exist with the name:
Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM) (Orchestration)
vs.
Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
This changes the image regexp to ignore them so we get the regular OS
image without Puppet, instead of needing to upgrade/downgrade from the
preinstalled version.
> Don't use Rackspace Orchestration images

- README.md
- fb-install-foreman.bats
FOREMAN_EXPECTED_VERSION can now be passed to the fb-install-foreman
test, which causes it to check all VERSION files match this exact
version number. This can be used for release testing to check all
packages were built and the correct ones are being tested.
---
Generates this output when tested with `FOREMAN_EXPECTED_VERSION=1.12.0-RC1` against RC2:
<pre>
✗ assert correct Foreman version is installed
(in test file /usr/bin/fb-install-foreman.bats, line 153)
`[ -n "$FOREMAN_EXPECTED_VERSION" ] || skip "FOREMAN_EXPECTED_VERSION is not set, not asserting"' failed
/usr/share/foreman-installer/VERSION:1.12.0-RC2
/usr/share/foreman-proxy/VERSION:1.12.0-RC2
/usr/share/foreman/VERSION:1.12.0-RC2
</pre>
> Add test to check Foreman is expected version

- fb-install-puppet.bats
Per [puppet-dev](https://groups.google.com/d/msg/puppet-dev/mHTsr_lvWwU/2Qm8nV08AAAJ), puppet5-nightly should now be preferred.
> Switch nightlies.pl.com to puppet5-nightly

- bootstrap_vagrant.sh
Rackspace Debian Stretch boxes are sometimes failing during bootstrap
with a locking error indicating the image's rc.local script is still
running dpkg/debconf commands:
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
dpkg: error processing package less (--configure):
subprocess installed post-installation script returned error exit status 1
Waiting until the completion of all boot stages, including cloud-init
and rc.local should ensure the bootstrap and tests themselves are the
only processes running.
> Wait for system boot completion before running package manager

- fb-install-foreman.bats
This should fix the errors currently seen on Debian/stretch systests. Rackspace did update their base image and it seems cloud-init does not set these entires in /etc/hosts anymore.
> add entires to /etc/hosts on Debian

- fb-install-foreman.bats
We have custom url for foreman, but not for plugins.
This causes failures when using koji because foreman-release
provides both foreman.repo and foreman-plugins.repo.
If you run the systest as a part of release process,
plugins repo points to the yum.theforeman.org instead of koji.
> Add custom plugins url when installing foreman
